import Link from "next/link";
import { Mail } from "lucide-react";

// Self-service registration has been retired — students now join via a
// personal invite link sent to their official college email, generated by
// Admin after uploading the registered-students list. See /complete-registration/[token].
export default function RegisterPage() {
  return (
    <div className="text-center py-6">
      <div className="w-14 h-14 rounded-full bg-primary-50 text-primary grid place-items-center mx-auto mb-4">
        <Mail size={24} />
      </div>
      <h1 className="text-xl font-bold mb-2">Registration is by invite only</h1>
      <p className="text-[13px] text-muted mb-6">
        You&apos;ll receive a registration link at your official college email once you&apos;re added to the placement list.
        Didn&apos;t get one? Reach out to the Placement Cell.
      </p>
      <Link href="/login" className="text-primary font-semibold text-[13px]">Go to Login</Link>
    </div>
  );
}